name: Context

on: [push]

jobs:
  one:
    runs-on: ubuntu-latest
    steps: 
      - name: Dumb Github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump step context
        env:
          STEP_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEP_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"